name: meet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python环境
  - python=3.8
  - pip>=20.0
  
  # 深度学习框架
  - pytorch>=1.7.0
  - torchvision>=0.8.0
  - cudatoolkit=11.1
  
  # 图像处理
  - opencv>=4.5.0
  - pillow>=8.0.0
  - scikit-image>=0.19.0
  
  # 科学计算
  - numpy>=1.19.2
  - scipy>=1.6.0
  - pandas>=1.3.0
  
  # 3D处理
  - open3d>=0.13.0
  
  # 工具库
  - tqdm>=4.50.0
  - matplotlib>=3.4.0
  - tensorboard>=2.6.0
  
  # 开发工具
  - pytest>=6.0
  - black>=21.0
  - flake8>=3.9
  - isort>=5.0
  
  # 网络相关
  - requests>=2.26.0
  - websockets>=10.0
  - flask>=2.0.0
  
  # 其他依赖
  - pip:
    - mediapipe>=0.8.9
    - moviepy>=1.0.3
    - face-recognition>=1.3.0
    - huggingface-hub>=0.4.0
    - transformers>=4.11.0
