name: meet-dev
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python基础环境
  - python=3.8
  - pip>=20.0
  
  # 核心依赖
  - pytorch>=1.7.0
  - torchvision>=0.8.0
  - cudatoolkit=11.1
  - opencv>=4.5.0
  - numpy>=1.19.2
  
  # 开发工具
  - pytest>=6.0
  - black>=21.0
  - flake8>=3.9
  - isort>=5.0
  
  # pip包
  - pip:
    - -r requirements/dev.txt

variables:
  PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:32"
  PYTHONPATH: "${PYTHONPATH}:${PWD}"
