name: meet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.7.0
  - torchvision>=0.8.0
  - cudatoolkit=11.1
  - opencv>=4.5.0
  - numpy>=1.19.2
  - pip:
    - -r requirements/prod.txt

variables:
  PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:32"
